CREATE TABLE IF NOT EXISTS `ARDUINO_001` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LUMINOSIDADE(%)` float NOT NULL,
  PRIMARY KEY (ID)
);
