USE Monitoramento;

DESC ARDUINO_001;

ALTER TABLE ARDUINO_001
ADD COLUMN `TEMPERATURA` float NOT NULL AFTER LUMINOSIDADE;

ALTER TABLE ARDUINO_001
ADD COLUMN `UMIDADE` float NOT NULL AFTER TEMPERATURA;

DESC ARDUINO_001;